version: "3.8"

services:
  app:
    build: .
    container_name: node-app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
